In [3]:
import numpy as np

"""
numpy = multidimensional arrays (1d, 2d, 3d, 4d)
- faster than lists ( uses fixed type, less bytes of memory to read, no type checking when iterating through objects )
- lists ( insertion, deletion, appending, concatenation ) numpy ( lots more )

applications - mathematics (MATLAB Replacemen), Plotting (Matplotlib), Backend( Pandas, Connect 4, Digital Photography, Machine Learning ) 
"""]

## The Basics

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[6.0,5.0,4.0], [3.0,2.0,1.0]])
print(b)

[[6. 5. 4.]
 [3. 2. 1.]]


In [9]:
#Get Dimension of a array
#Number dimensions 

a.ndim

1

In [13]:
#Get Shape
b.shape

(2, 3)

In [15]:
#Get type
a.dtype

dtype('int64')

In [16]:
#Get Size
a.itemsize

8

In [17]:
#Get total size 

a.nbytes

24

## Accesing/Chaning specific elements, rows, columns, etc

In [4]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#Get a specific element
a[1, 1]

np.int64(9)

In [9]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#Get a specific column
a[:, 3]

array([ 4, 11])

In [15]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 3:-1:2],

(array([4, 6]),)

In [19]:
a[0, 4] = 12
print(a)

[[ 1  2  3  4 12  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a[:,0] = [2,4]
print(a)

[[ 2  2  3  4 12  6  7]
 [ 4  9 10 11 12 13 14]]


In [22]:
#3d example

In [23]:
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
# 3 dimensions = 3 indexes to access an element
# b[layer, row, column]
# the size of each dimension doesn't matter, what counts is how many indexes you need

#Get specific element (work outside in) lrc
- layer
- row
- column


In [27]:
#get number 4
b[0, 1, 0]

np.int64(4)

In [33]:
#replace
b[:,1,:] = [[4,4,4],[2,2,2],[6,6,6]]

In [34]:
b

array([[[ 1,  2,  3],
        [ 4,  4,  4]],

       [[ 7,  8,  9],
        [ 2,  2,  2]],

       [[13, 14, 15],
        [ 6,  6,  6]]])

In [ ]:
##Initializing Different Types of Arrays