In [3]:
import numpy as np

"""
numpy = multidimensional arrays (1d, 2d, 3d, 4d)
- faster than lists ( uses fixed type, less bytes of memory to read, no type checking when iterating through objects )
- lists ( insertion, deletion, appending, concatenation ) numpy ( lots more )

applications - mathematics (MATLAB Replacemen), Plotting (Matplotlib), Backend( Pandas, Connect 4, Digital Photography, Machine Learning ) 
"""]

## The Basics

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[6.0,5.0,4.0], [3.0,2.0,1.0]])
print(b)

[[6. 5. 4.]
 [3. 2. 1.]]


In [9]:
#Get Dimension of a array
#Number dimensions 

a.ndim

1

In [13]:
#Get Shape
b.shape

(2, 3)

In [15]:
#Get type
a.dtype

dtype('int64')

In [16]:
#Get Size
a.itemsize

8

In [17]:
#Get total size 

a.nbytes

24

## Accesing/Chaning specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#Get a specific element
a[1, 1]

np.int64(9)

In [9]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#Get a specific column
a[:, 3]

array([ 4, 11])

In [29]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 3:-1:2]

array([4, 6])

In [19]:
a[0, 4] = 12
print(a)

[[ 1  2  3  4 12  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a[:,0] = [2,4]
print(a)

[[ 2  2  3  4 12  6  7]
 [ 4  9 10 11 12 13 14]]


In [22]:
#3d example

In [23]:
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
# 3 dimensions = 3 indexes to access an element
# b[layer, row, column]
# the size of each dimension doesn't matter, what counts is how many indexes you need

#Get specific element (work outside in) lrc
- layer
- row
- column


In [27]:
#get number 4
b[0, 1, 0]

np.int64(4)

In [33]:
#replace
b[:,1,:] = [[4,4,4],[2,2,2],[6,6,6]]

l,r,c

In [34]:
b

array([[[ 1,  2,  3],
        [ 4,  4,  4]],

       [[ 7,  8,  9],
        [ 2,  2,  2]],

       [[13, 14, 15],
        [ 6,  6,  6]]])

##Initializing Different Types of Arrays

In [5]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
#All 1s matrix
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
# Any other number
np.full((2,2), 44)

array([[44, 44],
       [44, 44]])

In [10]:
# Any other number (full_like)
#Creates an array with the same shape as an existing one, filled with a value you choose.
np.full_like(a, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [15]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.47034992, 0.49633832],
       [0.23741528, 0.20785596],
       [0.30747535, 0.10472561],
       [0.57108859, 0.49874504]])

In [22]:
#Random integer numbers
.random.randint(-4,4, size=(2,2))

array([[-4, -3],
       [-4,  3]])

In [24]:
#Creates an identity matrix, which is a square matrix with 1s on the diagonal and 0s everywhere else.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [28]:
#Repeats each element of an array a given number of times along a specified axis.
#axis=0 operates on rows (vertical), axis=1 operates on columns (horizontal)

arr = np.array([[1,2,3]])
r1= np.repeat(arr, 3, axis=1)
print(r1)


[[1 1 1 2 2 2 3 3 3]]


##Problem 1 Initialize the matrix below without entering the values one by one.

![descricao](image.png)

Initialize a 5x5 ones matrix with np.ones((5,5)), then a 3x3 zeros matrix with np.zeros((3,3)). Select the center of the ones matrix using output[1:4, 1:4] and assign the zeros matrix to it. The slice 1:4 selects indices 1, 2 and 3 on both axes, which matches the 3x3 shape of z. Think of it as cutting a square hole in the middle of the ones matrix and pasting the zeros matrix into it.


In [ ]:
# output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

           #R   #C
output[1:4, 1:4] = z
print(output)