In [2]:
import numpy as np

"""
numpy = multidimensional arrays (1d, 2d, 3d, 4d)
- faster than lists ( uses fixed type, less bytes of memory to read, no type checking when iterating through objects )
- lists ( insertion, deletion, appending, concatenation ) numpy ( lots more )

applications - mathematics (MATLAB Replacemen), Plotting (Matplotlib), Backend( Pandas, Connect 4, Digital Photography, Machine Learning ) 
"""]

## The Basics

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[6.0,5.0,4.0], [3.0,2.0,1.0]])
print(b)

[[6. 5. 4.]
 [3. 2. 1.]]


In [9]:
#Get Dimension of a array
#Number dimensions 

a.ndim

1

In [13]:
#Get Shape
b.shape

(2, 3)

In [15]:
#Get type
a.dtype

dtype('int64')

In [16]:
#Get Size
a.itemsize

8

In [17]:
#Get total size 

a.nbytes

24

## Accesing/Chaning specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element